set_languages("cxx23")
set_toolchains("clang")
add_requires("sfml 2.6.1", "boost", "tbb")
target("racingGame")
add_includedirs("include")
add_files("src/**.cpp")
add_packages("sfml", "boost", "tbb")
on_build(function(target)
	--- copy the resource files over ---
	print("Copying resources folder")
	os.cp("resources", "$(builddir)/$(plat)/$(arch)/$(mode)/resources")
end)
